# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
  - platform: template
    switches:
      television:
        value_template: '{{ not ((is_state("media_player.sky_q", "off") or is_state("media_player.sky_q", "unknown") or is_state("media_player.sky_q", "unavailable"))) }}'
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.sky_q
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.sky_q
        icon_template: >-
          {% if is_state("media_player.sky_q", "off") or is_state("media_player.sky_q", "unknown") %}
            mdi:television
          {% else %}
            mdi:television
          {% endif %}

sensor:
  #time transformations

  - platform: template
    sensors:
      dayoftheweek:
        value_template: "{{ now().strftime('%A') }}"

      month:
        value_template: "{{ now().strftime('%B') }}"

      dateofthemonth:
        value_template: >
          {% set suffix = ['st', 'nd', 'rd'] %}
          {% set day = now().day %}
          {% set index = 3 if day // 10 == 1 or day % 10 == 0 else (day % 10) - 1 %}
          {{ day~'th' if index > 2 else day~suffix[index] }}

  - platform: template
    sensors:
      sleep_h:
        value_template: >
          {% set ct = states('sensor.sleep_duration') | int %}
          {% if ct == 0 %}
            Unknown
          {% elif ct > 60 %}
            {{ ct // 60 }}:{{ '{:0>2d}'.format(ct%60) }} h
          {% else %}
            {{ ct }} min
          {% endif %}

  #presence
  - platform: template
    sensors:
      jesus_presence:
        friendly_name: "Jesus"
        value_template: >-
          {% if is_state("person.jesus", "home") %}
            home
          {% else %}
            away
          {% endif %}

  - platform: history_stats
    name: Jesus - Time at home
    entity_id: sensor.jesus_presence
    state: "home"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Jesus - Time away
    entity_id: sensor.jesus_presence
    state: "away"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  #sky_q

  - platform: template
    sensors:
      sky_q_on:
        value_template: >
          {% if is_state("media_player.sky_q","playing") or is_state("media_player.sky_q","paused") %}
            playing
          {% else %}
            off
          {% endif %}

  #peloton
  - platform: template
    sensors:
      peloton_state:
        value_template: >-
          {% if is_state("sensor.jesus_on_peloton_cadence_current","0") %}
            off
          {% else %}
            on
          {% endif %}

  - platform: systemmonitor
    resources:
      - type: disk_use
        arg: /config
      - type: disk_free
        arg: /config
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

#lights
light:
  - platform: group
    name: Living Room
    entities:
      - light.ceiling
      - light.floor_lamp

  - platform: group
    name: Bedroom
    entities:
      - light.bedside
      - light.bedroom_ceiling

  - platform: group
    name: All
    entities:
      - light.bedside
      - light.bedroom_ceiling
      - light.ceiling
      - light.floor_lamp

device_tracker:
  - platform: ping
    track_new_devices: False
    consider_home: 0:10
    hosts:
      kaari_iphone: 192.168.0.10
      kaaris_ipad: 192.168.0.20
      kaaris_apple_watch: 192.168.0.23

#vacuum cleaner
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.0.46
    token: !secret vacubot_token
    username: !secret vacubot_username
    password: !secret vacubot_password
    draw: ["all"]
    colors:
      color_map_outside: [32, 41, 60]
      color_path: [32, 41, 60]
      color_robo: [32, 41, 60]
    map_transformation:
      scale: 2
    attributes:
      - calibration_points

google_assistant:
  project_id: home-assistant-18814
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true

binary_sensor:
  - platform: ping
    host: 192.168.0.10
    name: "kaari's iPhone"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.0.20
    name: "kaari's iPad"
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.0.23
    name: "kaari's Apple Watch"
    count: 2
    scan_interval: 120

group:
  plants:
    name: plants
    entities:
      - plant.golden_pothos
      - plant.kentia_palm
      - plant.leaf_fig_tree
      - plant.parlor_palm
  all:
    name: all
    entities:
      - light.bedside
      - light.bedroom_ceiling
      - light.ceiling
      - light.floor_lamp
      - media_player.sky_q
